using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class EggInfo : MonoBehaviour
{
  public string[] EggGradeList = {"Null","Normal",
"Normal",
"Normal",
"Normal",
"Normal",
"Normal",
"Normal",
"Normal",
"Normal",
"Normal",
"Uncommon",
"Uncommon",
"Uncommon",
"Uncommon",
"Uncommon",
"Uncommon",
"Uncommon",
"Uncommon",
"Uncommon",
"Uncommon",
"Uncommon",
"Uncommon",
"Uncommon",
"Uncommon",
"Uncommon",
"Uncommon",
"Uncommon",
"Uncommon",
"Uncommon",
"Uncommon",
"Uncommon",
"Uncommon",
"Uncommon",
"Uncommon",
"Uncommon",
"Rare",
"Rare",
"Rare",
"Rare",
"Rare",
"Rare",
"Rare",
"Rare",
"Rare",
"Rare",
"Rare",
"Rare",
"Rare",
"Rare",
"Rare",
"Rare",
"Rare",
"Rare",
"Rare",
"Rare",
"Epic",
"Epic",
"Epic",
"Epic",
"Epic",
"Epic",
"Epic",
"Epic",
"Epic",
"Epic",
"Epic",
"Epic",
"Epic",
"Epic",
"Epic",
"Epic",
"Epic",
"Epic",
"Epic",
"Epic",
"Epic",
"Epic",
"Epic",
"Epic",
"Epic",
"Epic",
"Epic",
"Epic",
"Epic",
"Epic",
"Epic",
"Epic",
"Epic",
"Epic",
"Epic",
"Epic",
"Epic",
"Legendary",
"Legendary",
"Legendary",
"Legendary",
"Legendary",
"Legendary",
"Legendary",
"Legendary"};
  public string[] EggDescription = { "null", "given by default",
"given by default",
"given by default",
"given by default",
"given by default",
"given by default",
"given by default",
"given by default",
"given by default",
"given by default",
"If you explore the village, you'll get it",
"If you explore the village, you'll get it",
"If you explore the village, you'll get it",
"If you explore the village, you'll get it",
"If you explore the village, you'll get it",
"If you clear stage B, you'll get a high probability?",
"If you clear stage B, you'll get a high probability?",
"If you clear stage B, you'll get a high probability?",
"If you clear stage B, you'll get a high probability?",
"If you clear stage B, you'll get a high probability?",
"If you clear stage C, you'll get a high probability?",
"If you clear stage C, you'll get a high probability?",
"If you clear stage C, you'll get a high probability?",
"If you clear stage C, you'll get a high probability?",
"If you clear stage C, you'll get a high probability?",
"If you clear stage D, you'll get a high probability?",
"If you clear stage D, you'll get a high probability?",
"If you clear stage D, you'll get a high probability?",
"If you clear stage D, you'll get a high probability?",
"If you clear stage D, you'll get a high probability?",
"If you clear stage E, you'll get a high probability?",
"If you clear stage E, you'll get a high probability?",
"If you clear stage E, you'll get a high probability?",
"If you clear stage E, you'll get a high probability?",
"If you clear stage E, you'll get a high probability?",
"If you clear stage B, you'll get a low probability?",
"If you clear stage B, you'll get a low probability?",
"If you clear stage B, you'll get a low probability?",
"If you clear stage B, you'll get a low probability?",
"If you clear stage B, you'll get a low probability?",
"If you clear stage C, you'll get a low probability?",
"If you clear stage C, you'll get a low probability?",
"If you clear stage C, you'll get a low probability?",
"If you clear stage C, you'll get a low probability?",
"If you clear stage C, you'll get a low probability?",
"If you clear stage D, you'll get a low probability?",
"If you clear stage D, you'll get a low probability?",
"If you clear stage D, you'll get a low probability?",
"If you clear stage D, you'll get a low probability?",
"If you clear stage D, you'll get a low probability?",
"If you clear stage E, you'll get a low probability?",
"If you clear stage E, you'll get a low probability?",
"If you clear stage E, you'll get a low probability?",
"If you clear stage E, you'll get a low probability?",
"If you clear stage E, you'll get a low probability?",
"You can get it if you achieve certain achievements in Village!",
"You can get it if you achieve certain achievements in Village!",
"You can get it if you achieve certain achievements in Village!",
"You can get it if you achieve certain achievements in Village!",
"You can get it if you achieve certain achievements in Village!",
"You can get it if you achieve certain achievements in Stage B!",
"It's an egg that will be given to the top 30% of the Stage B team rankings after the weekly settlement!",
"It's an egg that will be given to the top 20% of the Stage B team rankings after the weekly settlement!",
"It's an egg that will be given to the top 10% of the Stage B team rankings after the weekly settlement!",
"You can get it if you achieve certain achievements in Stage B!",
"It's an egg that will be given to the top 30% of the Stage B individual rankings after the weekly settlement!",
"It's an egg that will be given to the top 20% of the Stage B individual rankings after the weekly settlement!",
"It's an egg that will be given to the top 10% of the Stage B individual rankings after the weekly settlement!",
"You can get it if you achieve certain achievements in Stage C!",
"It's an egg that will be given to the top 30% of the Stage C team rankings after the weekly settlement!",
"It's an egg that will be given to the top 20% of the Stage C team rankings after the weekly settlement!",
"It's an egg that will be given to the top 10% of the Stage C team rankings after the weekly settlement!",
"You can get it if you achieve certain achievements in Stage C!",
"It's an egg that will be given to the top 30% of the Stage C individual rankings after the weekly settlement!",
"It's an egg that will be given to the top 20% of the Stage C individual rankings after the weekly settlement!",
"It's an egg that will be given to the top 10% of the Stage C individual rankings after the weekly settlement!",
"You can get it if you achieve certain achievements in Stage D!",
"It's an egg that will be given to the top 30% of the Stage D team rankings after the weekly settlement!",
"It's an egg that will be given to the top 20% of the Stage D team rankings after the weekly settlement!",
"It's an egg that will be given to the top 10% of the Stage D team rankings after the weekly settlement!",
"You can get it if you achieve certain achievements in Stage D!",
"It's an egg that will be given to the top 30% of the Stage D individual rankings after the weekly settlement!",
"It's an egg that will be given to the top 20% of the Stage D individual rankings after the weekly settlement!",
"It's an egg that will be given to the top 10% of the Stage D individual rankings after the weekly settlement!",
"You can get it if you achieve certain achievements in Stage E!",
"It's an egg that will be given to the top 30% of the Stage E team rankings after the weekly settlement!",
"It's an egg that will be given to the top 20% of the Stage E team rankings after the weekly settlement!",
"It's an egg that will be given to the top 10% of the Stage E team rankings after the weekly settlement!",
"You can get it if you achieve certain achievements in Stage E!",
"It's an egg that will be given to the top 30% of the Stage E individual rankings after the weekly settlement!",
"It's an egg that will be given to the top 20% of the Stage E individual rankings after the weekly settlement!",
"It's an egg that will be given to the top 10% of the Stage E individual rankings after the weekly settlement!",
"Only the winner of the Stage B weekly team rankings can get it",
"Only the winner of the Stage B weekly individual rankings can get it",
"Only the winner of the Stage C weekly team rankings can get it",
"Only the winner of the Stage C weekly individual rankings can get it",
"Only the winner of the Stage D weekly team rankings can get it",
"Only the winner of the Stage D weekly individual rankings can get it",
"Only the winner of the Stage E weekly team rankings can get it",
"Only the winner of the Stage E weekly individual rankings can get it"};
}
